image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  DOCKER_DRIVER: overlay

cache:
  paths:
  - node_modules/

build-image:
  stage: build
  script:
  - docker build -t dto80/se234-lab11-client .
  - docker login -u xingyuankang -p XzBh6mqmM5rtxXF
  - docker push dto80/se234-lab11-client